import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";

import "./globals.css";

const abeezee = ABeeZee({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "meet-usvr-task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`abeezee.className antialiased`}>{children}</body>
    </html>
  );
}
